# File Name:  if_else_parser/makefile
# Build Date: Wed Apr 23 22:44:01 CDT 2025
# Version:    0.1.1

APP=lines
CXX=g++
CC=gcc
BISON=bison
LEX=flex
BISONFLAGS= -y -d --html --graph
CXXFLAGS=-Wall -std=c++17 -fPIC
CCFLAGS=
SRC=src
BLD?=build
OBJ?=build

# lib settings
LIBS=-L/usr/lib -L/usr/lib64 -L/usr/local/lib -L/usr/local/lib64
INCLUDES=-I/usr/local/include/cppunit/
LDFLAGS=$(INCLUDES) $(LIBS)

ifdef DEBUG
	CXXFLAGS += -DDEBUG
endif

ifdef CYGWIN
	CXXFLAGS +=-DCYGWIN
	LDFLAGS += -lfmt -lcppunit.dll
else
	LDFLAGS += -lfmt -lcppunit
endif

all: $(BLD)/ptest1

rebuild: clean all

$(BLD)/ptset1: $(BLD)/ptest1.tab.c $(BLD)/ptest1.yy.c
	 $(CC) $(CCFLAGS) $(BLD)/ptest1.tab.c $(BLD)/ptest1.yy.c -o $(BLD)/ptest1

$(BLD)/ptest1.yy.c: $(SRC)/ptest1.l
	$(LEX) -o $(BLD)/ptest1.yy.c $(SRC)/ptest1.l

$(BLD)/ptest1.tab.c: $(SRC)/ptest1.y
	$(BISON) -y $(BISONFLAGS) $(SRC)/ptest1.y -o $(BLD)/ptest1.tab.c

$(OBJ)/%.o: $(SRC)/%.c
	$(CC) $(CCFLAGS) -c -o $@ $<

.PHONY: clean
clean:
	-rm -f $(BLD)/*
	-rm -f $(OBJ)/*

.PHONY: help
help:
	@echo  '  all                        - build all'
	@echo  '  clean                      - remove all files from build dir'
