# @file: makefile
# @date: Wed, Jan 14, 2026 10:24:46 AM
# @version: 0.0.1

CXX=g++
BLD=build
SRC=.

all: $(BLD)/find_substrs

$(BLD)/find_substrs: $(SRC)/find_substrs.cpp
	$(CXX) -g -std=c++14 $^ -o $@ 

